services:
  # Web server
  - type: web
    name: sample_app_web
    plan: starter
    runtime: docker
    dockerfilePath: ./deploy/web/Dockerfile
    dockerContext: ./deploy/web
    preDeployCommand: ./deploy/web/pre_deploy.sh
    envVars:
      # 必要な環境変数の設定
  # DB
  - type: pserv
    name: sample_app_db
    plan: standard
    runtime: docker
    dockerfilePath: ./deploy/db/Dockerfile
    dockerContext: ./deploy/db/
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      # 必要な環境変数の設定
